[package]
name = "tower-defense"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = "0.12.0"
specs-derive = "0.4.0"

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
